#!/usr/bin/env php
<?php require_once __DIR__ . '/bootstrap.php';

use engine\admin\AdminModule;
use engine\articles\ArticlesModule;
use engine\comments\CommentsModule;
use engine\messages\MessagesModule;
use engine\statistics\StatisticsModule;
use engine\users\UsersModule;
use frame\config\ConfigRouter;
use frame\console\route\ConsoleRequest;
use frame\console\route\ConsoleRouter;
use frame\console\views\ConsoleViewRouter;
use frame\core\Core;
use frame\database\SqlDriver;
use frame\events\Events;
use frame\route\Router;
use frame\route\Request;
use frame\route\Response;
use frame\stdlib\configs\JsonConfig;
use frame\stdlib\configs\PhpConfig;
use frame\http\route\UrlResponse;
use frame\modules\Modules;
use frame\stdlib\drivers\database\MySqlDriver;
use frame\views\macros\ShowPage;
use frame\views\ViewRouter;

$app = new Core([
    Router::class => ConsoleRouter::class,
    Request::class => ConsoleRequest::class,
    Response::class => UrlResponse::class,
    ViewRouter::class => ConsoleViewRouter::class,
    SqlDriver::class => MySqlDriver::class
]);

$configRouter = ConfigRouter::getDriver();
$configRouter->addSupport([JsonConfig::class, PhpConfig::class]);

$modules = Modules::getDriver();
$modules->set(new StatisticsModule('stat'));
$modules->set(new AdminModule('admin'));
$modules->set(new UsersModule('users'));
$modules->set(new MessagesModule('messages'));
$modules->set($articles = new ArticlesModule('articles'));
$modules->set(new CommentsModule('comments', $articles));

$events = Events::getDriver();
$events->on(Core::EVENT_APP_START, new ShowPage);

$app->exec();