import setupReactComponent from './setup-app';
import QueryHistory from './components/database/query-history';
import DatabaseTables from './components/database/db-tables';
import ViewsHistory from './components/views/views-history';
import CashUseHistory from './components/cash/use-history';
import ArticlesTable from './components/articles-table';
import MessagesPage from './components/pages/messages';
import ProfilePage from './components/pages/profile';
import ModulesList from './components/modules/list';
import DialogsPage from './components/pages/dialogs';
import UsersTable from './components/users-table';
import LogPage from './components/pages/log';
import Comments from './components/comments';
import Form from './components/form/Form';
import Events from './components/events';
import Menu from './components/menu';

setupReactComponent('cash-use-history', CashUseHistory);
setupReactComponent('views-stat-page', ViewsHistory);
setupReactComponent('messages-page', MessagesPage);
setupReactComponent('query-history', QueryHistory);
setupReactComponent('messages-config-form', Form);
setupReactComponent('article-comments', Comments);
setupReactComponent('profile-page', ProfilePage);
setupReactComponent('db-tables', DatabaseTables);
setupReactComponent('dialog-list', DialogsPage);
setupReactComponent('rights-config-form', Form);
setupReactComponent('articles', ArticlesTable);
setupReactComponent('admin-config-form', Form);
setupReactComponent('profile-edit-form', Form);
setupReactComponent('stat-config-form', Form);
setupReactComponent('new-article-form', Form);
setupReactComponent('admin-login-form', Form);
setupReactComponent('group-edit-form', Form);
setupReactComponent('group-add-form', Form);
setupReactComponent('modules', ModulesList);
setupReactComponent('log-page', LogPage);
setupReactComponent('users', UsersTable);
setupReactComponent('events', Events);
setupReactComponent('menu', Menu);