import setupReactComponent from './setup-app';
import QueryHistory from './components/database/QueryHistory';
import DatabaseTables from './components/database/DatabaseTables';
import ViewHistory from './components/views/ViewHistory';
import ChartsPage from './components/stats/ChartsPage';
import ArticleTable from './components/articles/ArticleTable';
import MessageListPage from './components/messages/MessageListPage';
import AddUserPage from './components/users/AddUserPage';
import ProfilePage from './components/users/ProfilePage';
import ModulesList from './components/modules/ModuleList';
import DialogListPage from './components/messages/DialogListPage';
import UserTable from './components/users/UserTable';
import LogPage from './components/log/LogPage';
import CommentList from './components/comments/CommentList';
import Form from './components/form/Form';
import EventHistory from './components/events/EventHistory';
import Menu from './components/menu/menu';
import ArticlePage from './components/articles/ArticlePage';
import NewComments from './components/comments/NewCommentList';
import RouteHistory from './components/routes/RouteHistory';
import ActionHistory from './components/actions/ActionsHistory';
import CashUseHistory from './components/cash/CashUseHistory';

setupReactComponent('#stat-cash-history', CashUseHistory);
setupReactComponent('#stat-views-history', ViewHistory);
setupReactComponent('#stat-charts', ChartsPage);
setupReactComponent('#messages-page', MessageListPage);
setupReactComponent('#stat-routes-history', RouteHistory);
setupReactComponent('#stat-queries-history', QueryHistory);
setupReactComponent('#article-comments', CommentList);
setupReactComponent('#new-comments', NewComments);
setupReactComponent('#add-user-page', AddUserPage);
setupReactComponent('#profile-page', ProfilePage);
setupReactComponent('#db-tables', DatabaseTables);
setupReactComponent('#dialog-list', DialogListPage);
setupReactComponent('#articles', ArticleTable);
setupReactComponent('#modules', ModulesList);
setupReactComponent('#log-page', LogPage);
setupReactComponent('#users', UserTable);
setupReactComponent('#stat-events-history', EventHistory);
setupReactComponent('#menu', Menu);
setupReactComponent('#stat-actions-history', ActionHistory);
setupReactComponent('#article-page', ArticlePage);

setupReactComponent('.react-form', Form);